### ISSUE TITLE
localization_cues of COCO

### ISSUE THREAD

**Issue by 6clc** [halbielee/SEC_pytorch#2]
Can you tell me how do you get the localization_cues.pickle.gz of COCO ? Thanks.

**Comment by halbielee** [comment]
Hi @6clc!
Thank you for your attention and sorry for the late reply.

localization_cue.pickle is made by CAMs which are derived from the classification network.
This repository only contains the segmentation network for WSSS.

1. You need to train the classification network first for PascalVOC / COCO .
2. You can extract CAMs from the classification network.
3. You can aggregate extracted CAMs into one pickle file as 'localization_cues.pickle'

I am not sure if this answer is satisfactory to you. Please feel free to ask!

**Comment by 6clc** [comment]
Thanks. I will try.
